.github/workflows/build_docker.yml, puppetdb/Dockerfile
- add PUPPET_VERSION var
- build upon tag name
- allow to build puppet 8 and 7 versions
=> allow to build puppet 8 and 7 versions

README.md, puppetdb/docker-entrypoint.d/10-wait-for-hosts.sh
- remove offensive wording in variables where possible
- update parameter documentation
=> updates to documentation and variable naming

.github/workflows/build_docker.yml, build_versions.json
needs: https://github.com/voxpupuli/gha-build-and-publish-a-container/pull/25
fixes: https://github.com/voxpupuli/crafty/issues/5
=> Add matrix setup to build several versions in parallel specified in a json file

.github/workflows/build_docker.yml
fixes: https://github.com/voxpupuli/crafty/issues/6
=> Update build_arch to include linux/arm64

.gitignore, CHANGELOG.md, Gemfile, README.md, Rakefile
- Add Changelog
- Pin Gems for Changelog
- Update .gitignore
- Add Rakefile
- Update Docu
fixes: #20
=> Release v1.0.0

.github/workflows/build_docker.yml
fixes: https://github.com/voxpupuli/crafty/issues/7
=> also push to dockerhub

README.md
- use container from github
- a contributing link
fixes: #18
=> Update Readme to use containers from github and add contributing link

puppetdb/Dockerfile
see: https://docs.oracle.com/en/java/javase/11/jrockit-hotspot/logging.html#GUID-33074D03-B4F3-4D16-B9B6-8B0076661AAF
=> Use correct Xlog:gc syntax

puppetdb/Dockerfile, puppetdb/ssl.sh, puppetdb/wtfc.sh
fixes https://github.com/voxpupuli/crafty/issues/17
=> incorporate remote scripts

.github/workflows/ci.yaml
=> add shellcheck from reusable workflow

.github/workflows/build_docker.yml
add latest tags as in container-puppetserver so we also have 7.15.0-latest here
=> Add $version-latest tags for Docker images like in puppetserver

.markdownlint.json, README.md
- add markdownlint rules file
- allow br tags
- set line length to 185
- fix code block
- rearrange links
- add transfer notice
- add badge for puppet
=> update readme, add markdownlint rules

README.md
=> update container links

puppetdb/conf.d/puppetdb.conf
=> disable update check

puppetdb/conf.d/puppetdb.conf
=> quote boolean to be string; disable-update-checking has to be a string

README.md, puppetdb/Dockerfile, puppetdb/conf.d/.dockerenv, puppetdb/docker-entrypoint.sh
=> remove .dockerenv, add it as ENV to Dockerfile

build_versions.json
This PR updates the build versions to the latest stable releases for OSS.
=> Enhancement: update puppetdb to 7.18.0 and 8.5.0

build_versions.json
Fixes https://github.com/puppetlabs/puppetdb/issues/3966.
=> Update puppetdb to 8.5.1

.github/dependabot.yml, .github/release.yml, .github/workflows/release.yml, .gitignore, Gemfile
=> modulesync 

.github/workflows/build_docker.yml
Fixes: https://github.com/voxpupuli/crafty/issues/61
=> Use short container names

README.md
https://github.com/voxpupuli/container-puppetdb/blob/ed9df5e104ab7db175d746b51cc27634021ff7af/puppetdb/Dockerfile#L33
=> Fix docs of PUPPETDB_JAVA_ARGS

.github/workflows/ci.yaml
- so we only have to approve them
- enables the github feature auto-merge
- only add this if tests pass
=>     feat: enable the auto-merge feature on dependabot prs

puppetdb/docker-entrypoint.d/30-certificate-allowlist.sh
=> use correct name for certificate-allowlist
